name:                composite-realworld
version:             0.0.0.1
synopsis:            RealWorld backend using Servant and Composite
description:         Backend implementation of the RealWorld project with Servant and Composite
homepage:            https://github.com/jkachmar/composite-realworld
license:             MIT
author:              jkachmar
copyright:           2017 Joe Kachmar
category:            Web

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings

dependencies:
  - aeson               >= 1.0  && < 1.1
  - base                >= 4.7  && < 5
  - bytestring          >= 0.10 && < 0.11
  - classy-prelude      >= 1.2  && < 1.3
  - composite-aeson     # version pinned by stack.yaml
  - composite-base      # version pinned by stack.yaml
  - composite-opaleye   # version pinned by stack.yaml
  - cryptonite          # version pinned by stack.yaml
  - dotenv              # version pinned by stack.yaml
  - errors              >= 2.1  && < 2.2
  - fast-logger         >= 2.4  && < 2.5
  - jose                >= 0.5  && < 0.6
  - lens                >= 4.15 && < 4.16
  - monad-logger        >= 0.3  && < 0.4
  - mtl                 >= 2.2  && < 2.3
  - opaleye             >= 0.5  && < 0.6
  - postgresql-simple   >= 0.5  && < 0.6
  - product-profunctors >= 0.7  && < 0.8
  - profunctors         >= 5.2  && < 5.3
  - resource-pool       >= 0.2  && < 0.3
  - servant             # version pinned by stack.yaml
  - servant-auth        # version pinned by stack.yaml
  - servant-auth-server # version pinned by stack.yaml
  - servant-server      # version pinned by stack.yaml
  - transformers        >= 0.5  && < 0.6
  - time                >= 1.6  && < 1.7
  - text                >= 1.2  && < 1.3
  - uuid                >= 1.3  && < 1.4
  - wai                 >= 3.2  && < 3.3
  - wai-extra           >= 3.0  && < 3.1
  - warp                >= 3.2  && < 3.3
  - x509                >= 1.6  && < 1.7
  - x509-store          >= 1.6  && < 1.7

ghc-options:
  - -Wall
  # - -Werror

executables:
  composite-realworld-refurb:
    source-dirs:      migrations
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - refurb # version defined in stack.yaml

executables:
  composite-realworld-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      
      - -threaded 
      - -rtsopts 
      - -with-rtsopts=-N

    dependencies:
      - composite-realworld

library:
  source-dirs:        src
